### PR TITLE
Add miss test case of proxy_lib_SUITE

### PR DESCRIPTION
**Pull request by vkatsuba**
Related to https://github.com/travelping/ergw/pull/268. Added missing test case in `proxy_lib_SUITE` and updated configuration for correct checking of `ergw_proxy_lib:choose_gw/4` function.

### CODE REVIEW

**Review by ebengt — APPROVED** [review]
Looks good

**Review by RoadRunnr — COMMENTED** [review]
adding a guard condition to the wildcard catch in `ergw_proxy_lib:choose_gw([], _NodeSelect, _Version, _Socket)` would make this more complete.

**Comment by vkatsuba** [comment]
> adding a guard condition to the wildcard catch in `ergw_proxy_lib:choose_gw([], _NodeSelect, _Version, _Socket)` would make this more complete.

If I got your point correct - done.

**Review by RoadRunnr — APPROVED** [review]
LGTM

**Pull request merged**
