### PR TITLE
feature: ergw distributed cluster

### PR DESCRIPTION
**Pull request by RoadRunnr**

### CODE REVIEW

**Comment by vkatsuba** [comment]
Looks like some `rebar.lock` conflicts

**Comment by vkatsuba** [comment]
Please, explain:
- Why `k8s_dist` was added into `apps`? 
- Why `k8s_dist` was not moved into some separate application in a separate repository?

**Comment by vkatsuba** [comment]
It would be nice to have some documentation with description of configuration with build/running the `riak`/`k8s_dist` for different cases for `erGW`.

**Comment by vkatsuba** [comment]
Is this all information(`/run/secrets/`, `"kubernetes.default", 443`) immutable? Maybe make sense move it into some config section for case when we will needed to change it for some cases?

**Comment by RoadRunnr** [comment]
> Is this all information(`/run/secrets/`, `"kubernetes.default", 443`) immutable? Maybe make sense move it into some config section for case when we will needed to change it for some cases?

k8s API endpoint and file locations are immutable, AFAIK. Especially the cluster internal endpoints do not change.

**Review by vkatsuba — APPROVED** [review]

**Pull request merged**
