### PR TITLE
updated rebar.config to point to new ergw_aaa tag

### PR DESCRIPTION
**Pull request by vijay-hirani**
updated the ergw_aaa reference to 3.5.0 in rebar.config.

### CODE REVIEW

**Comment by mgumz** [comment]
@vijay-hirani last time ergw_aaa was touched, rebar.lock changed as well … see cfe4793ec08fbacdc8a568f07e2bdc208bd65508

**Comment by vijay-hirani** [comment]
@mgumz dependancies updated in rebar.lock

**Comment by RoadRunnr** [comment]
please squash the changes and use a sensibel commit message

**Comment by RoadRunnr** [comment]
I said squash the changes, not to lose the rebar.lock changes.

**Comment by vijay-hirani** [comment]
Fixed, squashed with the latest files

**Pull request merged**
