### PR TITLE
Add delete_request/1 function

### PR DESCRIPTION
**Pull request by vkatsuba**
Added `delete_request/1` API function for sending `DOWN` message in info handle: https://github.com/travelping/ergw/blob/master/src/pgw_s5s8_proxy.erl#L193-L196

### CODE REVIEW

**Review by RoadRunnr — CHANGES_REQUESTED** [review]
No. Rejected!

Exporting a function that sends a kill signal to a random process is of no use.

* if used from Erlang shell, the exit can be used without the export,
* there is no user for this in ergw

What is this good for, anyway?

**Comment by vkatsuba** [comment]
> No. Rejected!
> 
> Exporting a function that sends a kill signal to a random process is of no use.
> 
>     * if used from Erlang shell, the exit can be used without the export,
> 
>     * there is no user for this in ergw
> 
> 
> What is this good for, anyway?

Agree. I was implemented it for trigger:
```erlang
%...
    initiate_session_teardown(sgw2pgw, Data),
    initiate_session_teardown(pgw2sgw, Data),
    delete_forward_session(upf_failure, Data),
%...
```
in https://github.com/travelping/ergw/blob/master/src/pgw_s5s8_proxy.erl#L193-L196. I still cannot find more better approach, if you have any idea for implementation of delete request, please share with this.

**Comment by RoadRunnr** [comment]
providing an implementation for https://github.com/travelping/ergw/blob/master/src/pgw_s5s8_proxy.erl#L168-L170 and https://github.com/travelping/ergw/blob/master/src/ggsn_gn_proxy.erl#L187-L189 should enable `ergw_api:delete_contexts/1` to work on proxies.

**Comment by mgumz** [comment]
@vkatsuba the `exit(<pid>, kill)` idea was there to circumvent the fact that `delete_context` in the specific proxy implementation is not implemented. 

the proper implementation should 

https://github.com/travelping/ergw/blob/master/src/pgw_s5s8_proxy.erl#L193-L196
```
    initiate_session_teardown(sgw2pgw, Data),
    initiate_session_teardown(pgw2sgw, Data),
    delete_forward_session(upf_failure, Data),
```
in the handler for `delete_context` where it currently states:

```
handle_event({call, From}, delete_context, _State, _Data) ->
    ?LOG(warning, "delete_context no handled(yet)"),
    {keep_state_and_data, [{reply, From, ok}]};
```

**Comment by vkatsuba** [comment]
Closed this nonsense PR by reason that the issue was misunderstanded. Will be provided new implementation in new correct branch.

**Comment by vkatsuba** [comment]
> @vkatsuba the `exit(<pid>, kill)` idea was there to circumvent the fact that `delete_context` in the specific proxy implementation is not implemented.
> 
> the proper implementation should
> 
> https://github.com/travelping/ergw/blob/master/src/pgw_s5s8_proxy.erl#L193-L196
> 
> ```
>     initiate_session_teardown(sgw2pgw, Data),
>     initiate_session_teardown(pgw2sgw, Data),
>     delete_forward_session(upf_failure, Data),
> ```
> 
> in the handler for `delete_context` where it currently states:
> 
> ```
> handle_event({call, From}, delete_context, _State, _Data) ->
>     ?LOG(warning, "delete_context no handled(yet)"),
>     {keep_state_and_data, [{reply, From, ok}]};
> ```

Thanks. The @fholzhauser provided me deep details about it. I Close this PR and will provide correct implementation in new branch.

**Pull request closed without merging**
