### PR TITLE
Added semver

### PR DESCRIPTION
**Pull request by vkatsuba**
Added [SemVer](https://semver.org/) for `erGw` for skip step of change `rebar.config` each time when version of project will update.

### CODE REVIEW

**Review by mgumz — APPROVED** [review]
LGTM

**Comment by RoadRunnr** [comment]
@mgumz this result in version ids like `2.7.1+build.861.refa04f878`. Not sure what a tag based build will look like.

**Comment by vkatsuba** [comment]
> @mgumz this result in version ids like `2.7.1+build.861.refa04f878`. Not sure what a tag based build will look like.

Not exactly, if the git log is clear will be build X.X.X version, please try clone this branch in new folder and try `rebar3 as prod tar`

**Review by RoadRunnr — APPROVED** [review]
LGTM

**Pull request merged**
