### PR TITLE
fix return values of ergw_node_selection:lookup/{2,3}

### PR DESCRIPTION
**Pull request by RoadRunnr**
The two functions have very different return values, but used
an internal helper that would return a value that is unsuitable
for lookup/2.

The helper actually doesn't add much value to the implementation.
Unroll it into the actual functions and fix the return values.

This PR can be backported to all stable branches and should apply without much problems.

### CODE REVIEW

**Comment by javiermtorres** [comment]
Is it possible to add a unit test the check that this value is received in ergw_sx_node appropriately?

**Comment by mgumz** [comment]
what kind of effect does this commit fix? an observed issue in production?

at the moment its hard for me to relate this commit to anything in the past which would require a backport.

**Comment by mgumz** [comment]
repository wise: ergw_internal?

**Comment by RoadRunnr** [comment]
wrong repo

**Pull request closed without merging**
