### PR TITLE
Fix proxy gw selection when a gw is down

### PR DESCRIPTION
**Pull request by fholzhauser**

### CODE REVIEW

**Comment by vkatsuba** [comment]
Good catch! Maybe make sense add some test case for this fix?

**Comment by fholzhauser** [comment]
This is a fairly trivial/safe fix and also needed with some urgency. Extending CT to cover this previously missed scenario is planned in a follow up PR.

**Review by vkatsuba — APPROVED** [review]

**Review by ebengt — COMMENTED** [review]
Looks good

**Comment by RoadRunnr** [comment]
> This is a fairly trivial/safe fix and also needed with some urgency. Extending CT to cover this previously missed scenario is planned in a follow up PR.

The interesting thing is that this line was actually hit by the tests, but the catch all a few lines above hide the problem.

In fact adding a `when is_record(Socket, socket)` to the catch all would have made the unit tests fail.

**Comment by vkatsuba** [comment]
> The interesting thing is that this line was actually hit by the tests, but the catch all a few lines above hide the problem.
> 
> In fact adding a `when is_record(Socket, socket)` to the catch all would have made the unit tests fail.

Currently the checking of socket record already exist in choose_gw/4 however the test cases in `proxy_lib_SUITE` don't crashed by reason that in node_selection section provided one by one node. For raise an error like `function_clause` need add into config section `node_selection` two nodes where first node is invalid and next node is valid, using this configuration example CT in previous version can raise an error like  `function_clause` for case if `choose_gw/4` will be called as `choose_gw(Next, NodeSelect, Socket, Version)` instead of expected `choose_gw(Next, NodeSelect, Version, Socket)`. PR https://github.com/travelping/ergw/pull/270 witch updating of CT was provided.

**Pull request merged**
