### PR TITLE
Feature create session metrics

### PR DESCRIPTION
**Pull request by ebengt**
Feedback wanted. I have run this code in epc-05 and it counts requests from sgsnemu correctly. The user_authentication_failed response is also counted correctly. I need to create a new config before I can get request_accepted, but feedback will be valuable even without request_accepted counted.

### CODE REVIEW

**Comment by mgumz** [comment]
@ebengt can you show some sample output of the metrics as they show up in the prometheus format?

**Comment by ebengt** [comment]
Sorry, but I have only tested in epc-05. Is there a Prometheus running
there? Is there an IP address/port for Prometheus? Do I need credentials to
use it?

**Comment by tlnd** [comment]
@ebengt See the existing [description for the metrics](https://github.com/travelping/ergw/blob/master/METRICS.md) , at the bottom you find examples how to query metrics via the API endpoint.

**Comment by ebengt** [comment]
Sample (most old/existing metrics deleted):
...deleted
# TYPE path_epc_192_168_3_2_tx_v1_echo_response_count counter
path_epc_192_168_3_2_tx_v1_echo_response_count 1

# TYPE pdp_context_create_request counter
pdp_context_create_request 1

# TYPE pdp_context_create_response_mandatory_ie_missing counter
pdp_context_create_response_mandatory_ie_missing 0

# TYPE pdp_context_create_response_missing_or_unknown_apn counter
pdp_context_create_response_missing_or_unknown_apn 0

# TYPE pdp_context_create_response_rejected counter
pdp_context_create_response_rejected 0

# TYPE pdp_context_create_response_request_accepted counter
pdp_context_create_response_request_accepted 0

# TYPE pdp_context_create_response_system_failure counter
pdp_context_create_response_system_failure 0

# TYPE pdp_context_create_response_user_authentication_failed counter
pdp_context_create_response_user_authentication_failed 1

# TYPE session_create_request counter
session_create_request 0

# TYPE session_create_response_mandatory_ie_missing counter
session_create_response_mandatory_ie_missing 0

# TYPE session_create_response_missing_or_unknown_apn counter
session_create_response_missing_or_unknown_apn 0

# TYPE session_create_response_rejected counter
session_create_response_rejected 0

# TYPE session_create_response_request_accepted counter
session_create_response_request_accepted 0

# TYPE session_create_response_system_failure counter
session_create_response_system_failure 0

# TYPE session_create_response_user_authentication_failed counter
session_create_response_user_authentication_failed 0

# TYPE socket_gtp_c_epc_pt_v1_create_pdp_context_request summary
socket_gtp_c_epc_pt_v1_create_pdp_context_request_count 0
... deleted

**Comment by RoadRunnr** [comment]
Sorry, but wrong approach. Counters are already handled for all request and response type in ergw_gtp_c_socket. Duplicating counter logic for specific request type is not the right way to go.

**Comment by ebengt** [comment]
Replaced by feature_tag_create_session_metrics

**Pull request closed without merging**
